# Generated by Django 5.2.7 on 2025-12-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arobyte', '0007_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='college_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='preprofessional',
            field=models.CharField(default='', max_length=100),
        ),
    ]
