# Generated by Django 5.2.7 on 2025-12-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arobyte', '0008_volunteer_college_name_volunteer_preprofessional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='college_name',
            field=models.CharField(default='', max_length=100, verbose_name='College/Company Name'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='preprofessional',
            field=models.CharField(default='', max_length=100, verbose_name='Preprofessional'),
        ),
    ]
